/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectkasir;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JDialog;
import javax.swing.JLabel;
import java.awt.BorderLayout;
import java.sql.Statement;

/**
 *
 * @author ASUS
 */
public class dataMember extends javax.swing.JFrame {

    /**
     * Creates new form dataMember
     */
DefaultTableModel model;
    
    public dataMember() {
        initComponents();
        String[] judul = {"ID","Nama","Alamat", "No HP", "Jenis Kelamin"};
        model = new DefaultTableModel(judul, 0);
        this.tabelDataMember.setModel(model);
        tampilkan();
    }
    
    private void tampilkan(){
        int row = this.tabelDataMember.getRowCount();
        for(int a=0; a<row; a++){
            model.removeRow(0);
        }
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/posdb", "root", "");
            ResultSet rs =cn.createStatement().executeQuery("SELECT * FROM datamember");
            while(rs.next()){
                String data [] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)};
                model.addRow(data);
            }
        } catch (SQLException ex){
            Logger.getLogger(dataMember.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        kartuMember = new javax.swing.JDialog();
        panelKartuMember = new javax.swing.JPanel();
        labelJudulDialogMember = new javax.swing.JLabel();
        labelNamaID = new javax.swing.JLabel();
        labelNamaMember = new javax.swing.JLabel();
        labelJenisKelaminDialog = new javax.swing.JLabel();
        labelLogoMemberKanan = new javax.swing.JLabel();
        labelLogoMemberKiri = new javax.swing.JLabel();
        labelShowIDMember = new javax.swing.JLabel();
        labelShowNamaMember = new javax.swing.JLabel();
        labelShowJenisKelaminMember = new javax.swing.JLabel();
        panelBackground = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelNoHp = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        inputNoHp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataMember = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        tblEditMember = new javax.swing.JButton();
        tblHapusMember = new javax.swing.JButton();
        tblSimpanMember = new javax.swing.JButton();
        labelAlamat = new javax.swing.JLabel();
        labelJenisKelamin = new javax.swing.JLabel();
        inputAlamat = new javax.swing.JTextField();
        inputJenisKelamin = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("DATA BARANG ARGOMART");

        panelKartuMember.setBackground(new java.awt.Color(255, 204, 204));

        labelJudulDialogMember.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        labelJudulDialogMember.setForeground(new java.awt.Color(255, 102, 102));
        labelJudulDialogMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJudulDialogMember.setText("MEMBER ARGO MART");

        labelNamaID.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        labelNamaID.setForeground(new java.awt.Color(255, 102, 102));
        labelNamaID.setText("ID");

        labelNamaMember.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        labelNamaMember.setForeground(new java.awt.Color(255, 102, 102));
        labelNamaMember.setText("Nama");

        labelJenisKelaminDialog.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        labelJenisKelaminDialog.setForeground(new java.awt.Color(255, 102, 102));
        labelJenisKelaminDialog.setText("Jenis Kelamin");

        labelLogoMemberKanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogoMemberKanan.setText("LOGO");

        labelLogoMemberKiri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogoMemberKiri.setText("LOGO");

        labelShowIDMember.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        labelShowIDMember.setForeground(new java.awt.Color(255, 102, 102));
        labelShowIDMember.setText("test");

        labelShowNamaMember.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        labelShowNamaMember.setForeground(new java.awt.Color(255, 102, 102));
        labelShowNamaMember.setText("test");

        labelShowJenisKelaminMember.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        labelShowJenisKelaminMember.setForeground(new java.awt.Color(255, 102, 102));
        labelShowJenisKelaminMember.setText("test");

        javax.swing.GroupLayout panelKartuMemberLayout = new javax.swing.GroupLayout(panelKartuMember);
        panelKartuMember.setLayout(panelKartuMemberLayout);
        panelKartuMemberLayout.setHorizontalGroup(
            panelKartuMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKartuMemberLayout.createSequentialGroup()
                .addGroup(panelKartuMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKartuMemberLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelKartuMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelJenisKelaminDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNamaMember, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNamaID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(panelKartuMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelShowIDMember, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelShowNamaMember, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelShowJenisKelaminMember, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelKartuMemberLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(labelLogoMemberKiri, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelJudulDialogMember, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelLogoMemberKanan, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelKartuMemberLayout.setVerticalGroup(
            panelKartuMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKartuMemberLayout.createSequentialGroup()
                .addGroup(panelKartuMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJudulDialogMember, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(labelLogoMemberKanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelLogoMemberKiri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(panelKartuMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaID)
                    .addComponent(labelShowIDMember))
                .addGap(18, 18, 18)
                .addGroup(panelKartuMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaMember)
                    .addComponent(labelShowNamaMember))
                .addGap(18, 18, 18)
                .addGroup(panelKartuMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJenisKelaminDialog)
                    .addComponent(labelShowJenisKelaminMember))
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout kartuMemberLayout = new javax.swing.GroupLayout(kartuMember.getContentPane());
        kartuMember.getContentPane().setLayout(kartuMemberLayout);
        kartuMemberLayout.setHorizontalGroup(
            kartuMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelKartuMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        kartuMemberLayout.setVerticalGroup(
            kartuMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelKartuMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATA MEMBER AGORMART");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setText("LOGO");

        labelNama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNama.setForeground(new java.awt.Color(255, 102, 102));
        labelNama.setText("Nama");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        labelNoHp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNoHp.setForeground(new java.awt.Color(255, 102, 102));
        labelNoHp.setText("No HP");

        inputNoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNoHpActionPerformed(evt);
            }
        });

        tabelDataMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tabelDataMember);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Pencarian Data");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        tblEditMember.setText("Edit");
        tblEditMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblEditMemberActionPerformed(evt);
            }
        });

        tblHapusMember.setText("Hapus");

        tblSimpanMember.setText("Simpan");
        tblSimpanMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblSimpanMemberActionPerformed(evt);
            }
        });

        labelAlamat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelAlamat.setForeground(new java.awt.Color(255, 102, 102));
        labelAlamat.setText("Alamat");

        labelJenisKelamin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelJenisKelamin.setForeground(new java.awt.Color(255, 102, 102));
        labelJenisKelamin.setText("Jenis Kelamin");

        inputJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tblSimpanMember, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputAlamat)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(inputNama, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                            .addComponent(inputNoHp)
                                            .addComponent(inputJenisKelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(tblEditMember, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tblHapusMember, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(57, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelNama)
                                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAlamat)
                            .addComponent(inputAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNoHp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelJenisKelamin)
                            .addComponent(inputJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(tblSimpanMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tblEditMember)
                            .addComponent(tblHapusMember))))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNoHpActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void tblEditMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblEditMemberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblEditMemberActionPerformed

    private void tblSimpanMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblSimpanMemberActionPerformed
        // TODO add your handling code here:
        String nama = inputNama.getText();
        String alamat = inputAlamat.getText();
        String noHP = inputNoHp.getText();
        String jenisKelamin = (String) inputJenisKelamin.getSelectedItem();

        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/posdb", "root", "");
            String query = "INSERT INTO datamember (nama, alamat, noHP, jenisKelamin) VALUES (?,?,?,?)";
            PreparedStatement ps = conn.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            ps.setString(1, nama);
            ps.setString(2, alamat);
            ps.setString(3, noHP);
            ps.setString(4, jenisKelamin);
            int result = ps.executeUpdate();
            
            if (result > 0) {
                ResultSet generatedKeys = ps.getGeneratedKeys();
                if(generatedKeys.next()){
                    int generatedID = generatedKeys.getInt(1);
                    
                    kartuMember infoDialog = new kartuMember();
                    infoDialog.setTitle("Data Saved");
                    infoDialog.setLayout(new BorderLayout());
                    infoDialog.add(new JLabel("ID: " + generatedID), BorderLayout.NORTH);
                    infoDialog.add(new JLabel("Nama: " + nama), BorderLayout.CENTER);
                    infoDialog.add(new JLabel("Jenis Kelamin: " + jenisKelamin), BorderLayout.SOUTH);
                    infoDialog.setSize(500, 300);
                    infoDialog.setVisible(true);
                }
                
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
                tampilkan();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data");
            }
            conn.close();
            ps.close();
        } catch (Exception ex) {
            Logger.getLogger(dataBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblSimpanMemberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputAlamat;
    private javax.swing.JComboBox<String> inputJenisKelamin;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputNoHp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JDialog kartuMember;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelJenisKelamin;
    private javax.swing.JLabel labelJenisKelaminDialog;
    private javax.swing.JLabel labelJudulDialogMember;
    private javax.swing.JLabel labelLogoMemberKanan;
    private javax.swing.JLabel labelLogoMemberKiri;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNamaID;
    private javax.swing.JLabel labelNamaMember;
    private javax.swing.JLabel labelNoHp;
    private javax.swing.JLabel labelShowIDMember;
    private javax.swing.JLabel labelShowJenisKelaminMember;
    private javax.swing.JLabel labelShowNamaMember;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelKartuMember;
    private javax.swing.JTable tabelDataMember;
    private javax.swing.JButton tblEditMember;
    private javax.swing.JButton tblHapusMember;
    private javax.swing.JButton tblSimpanMember;
    // End of variables declaration//GEN-END:variables
}
