/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectkasir;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class dataBarang extends javax.swing.JFrame {

    /**
     * Creates new form dataBarang
     */
    DefaultTableModel model;
    
    public dataBarang() {
        initComponents();
        String[] judul = {"ID Barang", "Nama Barang", "Harga Barang", "Stok Barang"};
        model = new DefaultTableModel(judul, 0);
        this.tabelDataBarang.setModel(model);
        tampilkan();
    }
    
    private void tampilkan(){
        int row = this.tabelDataBarang.getRowCount();
        for(int a=0; a<row; a++){
            model.removeRow(0);
        }
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/posdb", "root", "");
            ResultSet rs =cn.createStatement().executeQuery("SELECT * FROM databarang");
            while(rs.next()){
                String data [] = {rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)};
                model.addRow(data);
            }
        } catch (SQLException ex){
            Logger.getLogger(dataBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editDataBarang = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        labelUpdateDataBarang = new javax.swing.JLabel();
        labelNamaBarangUPDATE = new javax.swing.JLabel();
        inputNamaBarangUPDATE = new javax.swing.JTextField();
        inputHargaBarangUPDATE = new javax.swing.JTextField();
        labelHargaUPDATE = new javax.swing.JLabel();
        labelStokBarangUPDATE = new javax.swing.JLabel();
        inputStokBarangUPDATE = new javax.swing.JTextField();
        tblUpdateDataBarang = new javax.swing.JButton();
        labelIDBarangTarget = new javax.swing.JLabel();
        inputIDBarangTarget = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelStok = new javax.swing.JLabel();
        labelHargaBarang = new javax.swing.JLabel();
        labelNamaBarang = new javax.swing.JLabel();
        inputIdBarang = new javax.swing.JTextField();
        inputHargaBarang = new javax.swing.JTextField();
        inputNamaBarang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataBarang = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        pencarianDataBarang = new javax.swing.JTextField();
        BtnEditDataBarang = new javax.swing.JButton();
        btnHapusDataBarang = new javax.swing.JButton();
        btnSimpanDataBarang = new javax.swing.JButton();
        labelIdBarang1 = new javax.swing.JLabel();
        inputStok = new javax.swing.JTextField();
        tblKeluar = new javax.swing.JButton();

        jPanel2.setForeground(new java.awt.Color(255, 204, 204));

        labelUpdateDataBarang.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        labelUpdateDataBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUpdateDataBarang.setText("UPDATE DATA BARANG");

        labelNamaBarangUPDATE.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        labelNamaBarangUPDATE.setText("NAMA");

        inputNamaBarangUPDATE.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N

        inputHargaBarangUPDATE.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N

        labelHargaUPDATE.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        labelHargaUPDATE.setText("HARGA");

        labelStokBarangUPDATE.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        labelStokBarangUPDATE.setText("STOCK");

        inputStokBarangUPDATE.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N

        tblUpdateDataBarang.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        tblUpdateDataBarang.setText("UPDATE");
        tblUpdateDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblUpdateDataBarangActionPerformed(evt);
            }
        });

        labelIDBarangTarget.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 12)); // NOI18N
        labelIDBarangTarget.setText("ID Barang Target");

        inputIDBarangTarget.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        inputIDBarangTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIDBarangTargetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelUpdateDataBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelIDBarangTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputIDBarangTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(labelHargaUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(inputHargaBarangUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(labelNamaBarangUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(inputNamaBarangUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(labelStokBarangUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(inputStokBarangUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tblUpdateDataBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUpdateDataBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelIDBarangTarget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputIDBarangTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNamaBarangUPDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputNamaBarangUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelHargaUPDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputHargaBarangUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelStokBarangUPDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputStokBarangUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tblUpdateDataBarang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout editDataBarangLayout = new javax.swing.GroupLayout(editDataBarang.getContentPane());
        editDataBarang.getContentPane().setLayout(editDataBarangLayout);
        editDataBarangLayout.setHorizontalGroup(
            editDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        editDataBarangLayout.setVerticalGroup(
            editDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("DATA BARANG ARGOMART");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setText("LOGO");

        labelStok.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelStok.setText("Stok");

        labelHargaBarang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelHargaBarang.setText("Harga Barang");

        labelNamaBarang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNamaBarang.setText("Nama Barang");

        inputHargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputHargaBarangActionPerformed(evt);
            }
        });

        inputNamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaBarangActionPerformed(evt);
            }
        });

        tabelDataBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tabelDataBarang);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Pencarian Data");

        pencarianDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianDataBarangActionPerformed(evt);
            }
        });

        BtnEditDataBarang.setText("Edit");
        BtnEditDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditDataBarangActionPerformed(evt);
            }
        });

        btnHapusDataBarang.setText("Hapus");
        btnHapusDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusDataBarangActionPerformed(evt);
            }
        });

        btnSimpanDataBarang.setText("Simpan");
        btnSimpanDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanDataBarangActionPerformed(evt);
            }
        });

        labelIdBarang1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelIdBarang1.setText("ID Barang");

        inputStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputStokActionPerformed(evt);
            }
        });

        tblKeluar.setText("Back");
        tblKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIdBarang1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelStok, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputStok, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnSimpanDataBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnEditDataBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapusDataBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tblKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(pencarianDataBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputIdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIdBarang1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNamaBarang)
                            .addComponent(inputNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHargaBarang)
                            .addComponent(inputHargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelStok)
                            .addComponent(inputStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSimpanDataBarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnEditDataBarang)
                            .addComponent(btnHapusDataBarang))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tblKeluar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(pencarianDataBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaBarangActionPerformed

    private void pencarianDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianDataBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pencarianDataBarangActionPerformed

    private void BtnEditDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditDataBarangActionPerformed
        // TODO add your handling code here:
        this.editDataBarang.setLocationRelativeTo(this);
        this.editDataBarang.setVisible(true);
        this.editDataBarang.setSize(380, 350);
        
    }//GEN-LAST:event_BtnEditDataBarangActionPerformed

    private void inputHargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputHargaBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputHargaBarangActionPerformed

    private void btnSimpanDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanDataBarangActionPerformed
        // TODO add your handling code here:
        String idBarang = inputIdBarang.getText();
        String namaBarang = inputNamaBarang.getText();
        String hargaBarang = inputHargaBarang.getText();
        String stokBarang = inputStok.getText();
        
//        hargaBarang = "Rp. " + hargaBarang;
        
        try{
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/posdb", "root", "");
            String query = "INSERT INTO databarang (idBarang, namaBarang, hargaBarang, stokBarang) VALUES (?,?,?,?)";
            PreparedStatement ps = conn.prepareStatement(query);
            ps.setString(1, idBarang);
            ps.setString(2, namaBarang);
            ps.setString(3, hargaBarang);
            ps.setString(4, stokBarang);
        int result = ps.executeUpdate();
            if(result > 0){
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
                tampilkan();
            } else{
                JOptionPane.showMessageDialog(this,"Gagal menyimpan data");
            }
            conn.close();
            ps.close();
        } catch (Exception ex) {
            Logger.getLogger(dataBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSimpanDataBarangActionPerformed

    private void btnHapusDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusDataBarangActionPerformed
        // TODO add your handling code here:
        int selectedRow = tabelDataBarang.getSelectedRow();
        
        if (selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus!");
        } else {
            String idbarangdelete = tabelDataBarang.getValueAt(selectedRow, 0).toString();
            
        model.removeRow(selectedRow);
            
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/posdb", "root", "");
            String query = "DELETE FROM databarang WHERE idBarang = ?";
            try (PreparedStatement ps = cn.prepareStatement(query)){
                ps.setString(1, idbarangdelete);
                int result = ps.executeUpdate();
                if (result >0){
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                    tampilkan();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data.");
                }
                ps.close();
           }
           cn.close();
        }catch (SQLException ex){
            Logger.getLogger(dataBarang.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghubungkan ke database.");
        }
        }
    }//GEN-LAST:event_btnHapusDataBarangActionPerformed

    private void inputStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputStokActionPerformed

    private void tblUpdateDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblUpdateDataBarangActionPerformed
        String url = "jdbc:mysql://localhost:3306/posdb";
        String user = "root";
        String password = "";

        try (Connection connection = DriverManager.getConnection(url, user, password)) {
            String noBukuTarget = this.inputIDBarangTarget.getText();
            String querySelect = "SELECT * FROM databarang WHERE idBarang=?";
            try (PreparedStatement preparedStatementSelect = connection.prepareStatement(querySelect)) {
                preparedStatementSelect.setString(1, noBukuTarget);
                ResultSet resultSet = preparedStatementSelect.executeQuery();

                if (resultSet.next()) {
                    String namaBarangLama = resultSet.getString("namaBarang");
                    String hargaBarangLama = resultSet.getString("hargaBarang");
                    String stokBarangLama = resultSet.getString("stokBarang");

                    String namaBarangBaru = this.inputNamaBarangUPDATE.getText();
                    String hargaBarangBaru = this.inputHargaBarangUPDATE.getText();
                    String stokBarangBaru = this.inputStokBarangUPDATE.getText();

                    if (!namaBarangLama.equals(namaBarangBaru) || !hargaBarangLama.equals(hargaBarangBaru) || !stokBarangLama.equals(stokBarangBaru)) {
                        String queryUpdate = "UPDATE databarang SET namaBarang=?, hargaBarang=?, stokBarang=? WHERE idBarang=?";
                        try (PreparedStatement preparedStatementUpdate = connection.prepareStatement(queryUpdate)) {
                            preparedStatementUpdate.setString(1, namaBarangBaru);
                            preparedStatementUpdate.setString(2, hargaBarangBaru);
                            preparedStatementUpdate.setString(3, stokBarangBaru);
                            preparedStatementUpdate.setString(4, noBukuTarget);

                            int result = preparedStatementUpdate.executeUpdate();
                            preparedStatementUpdate.close();

                            if (result > 0) {
                                JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                                tampilkan();
                            } else {
                                JOptionPane.showMessageDialog(this, "Gagal menyimpan data", "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Data tidak berubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Data tidak ditemukan", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal terhubung ke database", "Error", JOptionPane.ERROR_MESSAGE);
        }
        this.editDataBarang.dispose();
        
    }//GEN-LAST:event_tblUpdateDataBarangActionPerformed

    private void inputIDBarangTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIDBarangTargetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIDBarangTargetActionPerformed

    private void tblKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKeluarActionPerformed
        // TODO add your handling code here:
        menuPilihan menu = new menuPilihan();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tblKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditDataBarang;
    private javax.swing.JButton btnHapusDataBarang;
    private javax.swing.JButton btnSimpanDataBarang;
    private javax.swing.JDialog editDataBarang;
    private javax.swing.JTextField inputHargaBarang;
    private javax.swing.JTextField inputHargaBarangUPDATE;
    private javax.swing.JTextField inputIDBarangTarget;
    private javax.swing.JTextField inputIdBarang;
    private javax.swing.JTextField inputNamaBarang;
    private javax.swing.JTextField inputNamaBarangUPDATE;
    private javax.swing.JTextField inputStok;
    private javax.swing.JTextField inputStokBarangUPDATE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelHargaBarang;
    private javax.swing.JLabel labelHargaUPDATE;
    private javax.swing.JLabel labelIDBarangTarget;
    private javax.swing.JLabel labelIdBarang1;
    private javax.swing.JLabel labelNamaBarang;
    private javax.swing.JLabel labelNamaBarangUPDATE;
    private javax.swing.JLabel labelStok;
    private javax.swing.JLabel labelStokBarangUPDATE;
    private javax.swing.JLabel labelUpdateDataBarang;
    private javax.swing.JTextField pencarianDataBarang;
    private javax.swing.JTable tabelDataBarang;
    private javax.swing.JButton tblKeluar;
    private javax.swing.JButton tblUpdateDataBarang;
    // End of variables declaration//GEN-END:variables
}
