/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectkasir;

/**
 *
 * @author ASUS
 */
public class menuPilihan extends javax.swing.JFrame {

    /**
     * Creates new form menuPilihan
     */
    public menuPilihan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        labelJudulMenu = new javax.swing.JLabel();
        deskopInputData = new javax.swing.JDesktopPane();
        labelInputData = new javax.swing.JLabel();
        tblDataBarang = new javax.swing.JButton();
        tblDataMember = new javax.swing.JButton();
        deskopTransaksi = new javax.swing.JDesktopPane();
        labelTransaksi = new javax.swing.JLabel();
        tblProsesTransaksi = new javax.swing.JButton();
        tblRiwayatTransaksi = new javax.swing.JButton();
        tblKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panelBackground.setBackground(new java.awt.Color(255, 204, 204));

        labelJudulMenu.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 60)); // NOI18N
        labelJudulMenu.setForeground(new java.awt.Color(255, 102, 102));
        labelJudulMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJudulMenu.setText("ARGOMART");

        deskopInputData.setBackground(new java.awt.Color(255, 153, 153));
        deskopInputData.setForeground(new java.awt.Color(255, 102, 102));

        labelInputData.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        labelInputData.setForeground(new java.awt.Color(255, 255, 255));
        labelInputData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInputData.setText("INPUT DATA");

        tblDataBarang.setBackground(new java.awt.Color(255, 102, 102));
        tblDataBarang.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        tblDataBarang.setForeground(new java.awt.Color(255, 255, 255));
        tblDataBarang.setText("Data Barang");
        tblDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblDataBarangActionPerformed(evt);
            }
        });

        tblDataMember.setBackground(new java.awt.Color(255, 102, 102));
        tblDataMember.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        tblDataMember.setForeground(new java.awt.Color(255, 255, 255));
        tblDataMember.setText("Data Member");
        tblDataMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblDataMemberActionPerformed(evt);
            }
        });

        deskopInputData.setLayer(labelInputData, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskopInputData.setLayer(tblDataBarang, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskopInputData.setLayer(tblDataMember, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout deskopInputDataLayout = new javax.swing.GroupLayout(deskopInputData);
        deskopInputData.setLayout(deskopInputDataLayout);
        deskopInputDataLayout.setHorizontalGroup(
            deskopInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskopInputDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deskopInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelInputData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblDataBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblDataMember, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                .addContainerGap())
        );
        deskopInputDataLayout.setVerticalGroup(
            deskopInputDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskopInputDataLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelInputData, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tblDataBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tblDataMember, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deskopTransaksi.setBackground(new java.awt.Color(255, 153, 153));

        labelTransaksi.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        labelTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        labelTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTransaksi.setText("TRANSAKSI");

        tblProsesTransaksi.setBackground(new java.awt.Color(255, 102, 102));
        tblProsesTransaksi.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        tblProsesTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        tblProsesTransaksi.setText("Proses Transaksi");
        tblProsesTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblProsesTransaksiActionPerformed(evt);
            }
        });

        tblRiwayatTransaksi.setBackground(new java.awt.Color(255, 102, 102));
        tblRiwayatTransaksi.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        tblRiwayatTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        tblRiwayatTransaksi.setText("Riwayat Transaksi");
        tblRiwayatTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblRiwayatTransaksiActionPerformed(evt);
            }
        });

        deskopTransaksi.setLayer(labelTransaksi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskopTransaksi.setLayer(tblProsesTransaksi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskopTransaksi.setLayer(tblRiwayatTransaksi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout deskopTransaksiLayout = new javax.swing.GroupLayout(deskopTransaksi);
        deskopTransaksi.setLayout(deskopTransaksiLayout);
        deskopTransaksiLayout.setHorizontalGroup(
            deskopTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskopTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deskopTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblProsesTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tblRiwayatTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                .addContainerGap())
        );
        deskopTransaksiLayout.setVerticalGroup(
            deskopTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskopTransaksiLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tblProsesTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tblRiwayatTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        tblKeluar.setBackground(new java.awt.Color(255, 102, 102));
        tblKeluar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        tblKeluar.setForeground(new java.awt.Color(255, 255, 255));
        tblKeluar.setText("KELUAR");
        tblKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(deskopInputData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deskopTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addComponent(labelJudulMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tblKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJudulMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deskopInputData)
                    .addComponent(deskopTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tblKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblKeluarActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tblKeluarActionPerformed

    private void tblDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblDataBarangActionPerformed
        // TODO add your handling code here:
        dataBarang db = new dataBarang();
        db.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tblDataBarangActionPerformed

    private void tblDataMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblDataMemberActionPerformed
        // TODO add your handling code here:
        dataMember dm = new dataMember();
        dm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tblDataMemberActionPerformed

    private void tblProsesTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblProsesTransaksiActionPerformed
        // TODO add your handling code here:
        Transaksi tr = new Transaksi();
        tr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tblProsesTransaksiActionPerformed

    private void tblRiwayatTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblRiwayatTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblRiwayatTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPilihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPilihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPilihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPilihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPilihan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskopInputData;
    private javax.swing.JDesktopPane deskopTransaksi;
    private javax.swing.JLabel labelInputData;
    private javax.swing.JLabel labelJudulMenu;
    private javax.swing.JLabel labelTransaksi;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JButton tblDataBarang;
    private javax.swing.JButton tblDataMember;
    private javax.swing.JButton tblKeluar;
    private javax.swing.JButton tblProsesTransaksi;
    private javax.swing.JButton tblRiwayatTransaksi;
    // End of variables declaration//GEN-END:variables
}
