/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectkasir;

/**
 *
 * @author ASUS
 */
public class Transaksi extends javax.swing.JFrame {

    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHargaTotal = new javax.swing.JLabel();
        deskopFakturKodeBarang = new javax.swing.JDesktopPane();
        labelFaktur = new javax.swing.JLabel();
        labelKodeBarang = new javax.swing.JLabel();
        inptKodeBarang = new javax.swing.JTextField();
        inputHarga = new javax.swing.JTextField();
        inputNamaBarang1 = new javax.swing.JTextField();
        inputQty = new javax.swing.JTextField();
        inputTotalHargaItem = new javax.swing.JTextField();
        inputNoTrasaksi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelShow = new javax.swing.JTable();
        tblBayar = new javax.swing.JButton();
        tblHapus = new javax.swing.JButton();
        tblEdit = new javax.swing.JButton();
        labelJumlahHarga = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        labelDiskon = new javax.swing.JLabel();
        labelTotalHarga = new javax.swing.JLabel();
        inputJumlahHarga = new javax.swing.JTextField();
        inputDiskon = new javax.swing.JTextField();
        inputTotalHarga = new javax.swing.JTextField();
        inputStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelHargaTotal.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 48)); // NOI18N
        labelHargaTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelHargaTotal.setText("Rp.");

        labelFaktur.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        labelFaktur.setForeground(new java.awt.Color(255, 255, 255));
        labelFaktur.setText("No. Faktur");

        labelKodeBarang.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        labelKodeBarang.setForeground(new java.awt.Color(255, 255, 255));
        labelKodeBarang.setText("Kode Barang");

        inptKodeBarang.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N

        inputHarga.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N

        inputNamaBarang1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N

        inputQty.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N

        inputTotalHargaItem.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N

        inputNoTrasaksi.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N

        deskopFakturKodeBarang.setLayer(labelFaktur, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskopFakturKodeBarang.setLayer(labelKodeBarang, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskopFakturKodeBarang.setLayer(inptKodeBarang, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskopFakturKodeBarang.setLayer(inputHarga, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskopFakturKodeBarang.setLayer(inputNamaBarang1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskopFakturKodeBarang.setLayer(inputQty, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskopFakturKodeBarang.setLayer(inputTotalHargaItem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        deskopFakturKodeBarang.setLayer(inputNoTrasaksi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout deskopFakturKodeBarangLayout = new javax.swing.GroupLayout(deskopFakturKodeBarang);
        deskopFakturKodeBarang.setLayout(deskopFakturKodeBarangLayout);
        deskopFakturKodeBarangLayout.setHorizontalGroup(
            deskopFakturKodeBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskopFakturKodeBarangLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(deskopFakturKodeBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelFaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deskopFakturKodeBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inptKodeBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(inputNoTrasaksi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNamaBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputQty, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTotalHargaItem, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        deskopFakturKodeBarangLayout.setVerticalGroup(
            deskopFakturKodeBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskopFakturKodeBarangLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(deskopFakturKodeBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFaktur)
                    .addComponent(inputNoTrasaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(deskopFakturKodeBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKodeBarang)
                    .addComponent(inptKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNamaBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTotalHargaItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tabelShow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelShow);

        tblBayar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        tblBayar.setText("BAYAR");

        tblHapus.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        tblHapus.setText("HAPUS");

        tblEdit.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        tblEdit.setText("EDIT");

        labelJumlahHarga.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        labelJumlahHarga.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelJumlahHarga.setText("Jumlah Harga");

        labelStatus.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        labelStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelStatus.setText("Status");

        labelDiskon.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        labelDiskon.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDiskon.setText("Diskon %");

        labelTotalHarga.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        labelTotalHarga.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTotalHarga.setText("Total Harga");

        inputStatus.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        inputStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Member", "Non-Member" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelHargaTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deskopFakturKodeBarang)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tblBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tblHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tblEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(115, 115, 115)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelJumlahHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inputJumlahHarga))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inputDiskon))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(inputTotalHarga))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(inputStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelHargaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deskopFakturKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelJumlahHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(inputJumlahHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tblHapus)
                        .addComponent(tblEdit))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputTotalHarga)
                        .addGap(2, 2, 2)))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskopFakturKodeBarang;
    private javax.swing.JTextField inptKodeBarang;
    private javax.swing.JTextField inputDiskon;
    private javax.swing.JTextField inputHarga;
    private javax.swing.JTextField inputJumlahHarga;
    private javax.swing.JTextField inputNamaBarang1;
    private javax.swing.JTextField inputNoTrasaksi;
    private javax.swing.JTextField inputQty;
    private javax.swing.JComboBox<String> inputStatus;
    private javax.swing.JTextField inputTotalHarga;
    private javax.swing.JTextField inputTotalHargaItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDiskon;
    private javax.swing.JLabel labelFaktur;
    private javax.swing.JLabel labelHargaTotal;
    private javax.swing.JLabel labelJumlahHarga;
    private javax.swing.JLabel labelKodeBarang;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTotalHarga;
    private javax.swing.JTable tabelShow;
    private javax.swing.JButton tblBayar;
    private javax.swing.JButton tblEdit;
    private javax.swing.JButton tblHapus;
    // End of variables declaration//GEN-END:variables
}
